---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapira-api
  namespace: tapira
  labels:
    name: tapira
    backend: tapira-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tapira
      backend: tapira-api
  template:
    metadata:
      name: tapira-api-pods
      namespace: tapira
      labels:
        name: tapira
        backend: tapira-api
    spec:
      containers:
        - name: tapira-api-containers
          image: milamber97/tapira:0.1.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_USER
              valueFrom:
                  secretKeyRef:
                    name: mongo-creds
                    key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: mongodb_host
              value: mongo-nodeport-svc
            - name: mongodb_port
              value: "27017"
            - name: api_clarity_host
              value: postgrest.apiclarity #<<service_name>>.<<namespace>>
            - name: api_clarity_port
              value: "3000"