---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapira
  labels:
    name: tapira
  namespace: apiclarity
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tapira
  template:
    metadata:
      labels:
        name: tapira
    spec:
      containers:
        - name: tapira
          image: milamber97/tapira:mongodb_config
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_USER
              valueFrom:
                  secretKeyRef:
                    name: mongo-creds
                    key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: mongodb_host
              value: mongo-nodeport-svc
            - name: mongodb_port
              value: "27017"
            - name: api_clarity_host
              value: postgrest
            - name: api_clarity_port
              value: "3000"