apiVersion: v1
kind: Service
metadata:
  name: tapira-api
  namespace: tapira
  labels:
    backend: tapira-api
spec:
  selector:
    backend: tapira-api
  ports:
    - port: 5000
      targetPort: 5000