apiVersion: v1
kind: Service
metadata:
  name: tapira-client
  namespace: tapira
  labels:
    frontend: tapira-client
spec:
  selector:
    frontend: tapira-client
  ports:
    - port: 80
      targetPort: 80