apiVersion: v1
kind: Service
metadata:
  name: tapira
  labels:
    name: tapira
  namespace: tapira
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30002
  selector:
    name: tapira