apiVersion: v1
kind: Service
metadata:
 labels:
  app: apiclarity
 name: apiclarity-service-node
 namespace: apiclarity
spec:
 selector:
   app: Tapira-Apiclarity
   env: prod
 type: ClusterIP
 ports:
 - port: 9999
    protocol: TCP
    targetPort: 8080
    nodePort: 9999
