# copied from Hightower, K: Kubernetes: Up and Running

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: tapira
spec:
  ports: 
    - port: 27017
      name: peer
  clusterIP: None
  selector:
    app: mongo