apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: apiclarity
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi

#This one might not work for Tapira since we need to mapout the storage out of it
