---
info:
  description: Api for the TAPIRA backend
  contact:
    email: test@swagger.io
  license:
    name: MIT License
    url: https://fr.wikipedia.org/wiki/Licence_MIT
  title: TAPIRA_Api
  version: 0.1
paths:
  "/api/apiclarity_specs":
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiClaritySpecs"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Fetch provided and reconstructed specifications from APIClarity and
        save them in database.
      tags:
        - specs_api
  "/api/services":
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Services"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Get list of service names
      description: Return list of unique service names with existing specifications.
      tags:
        - specs_api
  "/api/versions":
    get:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Versions"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Get list of versions
      description: Return list of versions for a service.
      tags:
        - specs_api
  "/api/specifications":
    get:
      parameters:
        - in: query
          name: version
          required: false
          schema:
            type: string
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiSpecs"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Get filtered api specifications
      description: Filter api specifications based on parameters.
      tags:
        - specs_api
  "/api/current_version_spec":
    get:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiSpecEntry"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Get latest api specification
      description: Get latest api specification based on service name.
      tags:
        - specs_api
  "/api/upload":
    post:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UploadResponse"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              "$ref": "#/components/schemas/Upload"
      summary: Upload existing API specification
      description: Upload existing API specification and delete current proposals
        for the same service.
      tags:
        - specs_api
  "/api/service_proposals":
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Services"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Get list of service names
      description: Return list of unique service names with existing proposals for
        specifications.
      tags:
        - proposals_api
  "/api/proposal":
    get:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Proposal"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Get proposal for a service
      description: Get proposal by a service name.
      tags:
        - proposals_api
  "/api/housekeeping":
    delete:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Housekeeping"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Delete all proposals
      description: Delete all proposals
      tags:
        - proposals_api
  "/api/conflicts":
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Services"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Returns list of services with conflicts
      description: Returns list of services with conflicts. If none provided specs
        compare with empty.
      tags:
        - proposals_api
  "/api/conflict":
    get:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AllChangesComparison"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Finds conflicts between reconstructed and latest spec
      description: Finds conflicts between reconstructed and latest spec by using
        the ApiDiff service.
      tags:
        - proposals_api
  "/api/comparison":
    post:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AllChangesComparison"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              "$ref": "#/components/schemas/Upload"
      summary: Upload existing API specification
      description: Upload existing API specification and delete current proposals
        for the same service.
      tags:
        - comparison_api
  "/api/evolution":
    get:
      parameters:
        - in: query
          name: old_version
          required: true
          schema:
            type: string
        - in: query
          name: new_version
          required: true
          schema:
            type: string
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AllChangesComparison"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Compare api and tira diffs between two version of specifications for
        a service.
      description: Compare api and tira diffs between two version of specifications
        for a service.
      tags:
        - comparison_api
  "/api/proposed_merge":
    post:
      parameters:
        - in: query
          name: context
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProposedMergeRequestBody"
      summary: Get a proposed merge of both api specifications
      description: Get a proposed merge of both api specifications in the context
        of validation or comparison.
      tags:
        - merge_api
  "/test/housekeeping_specs":
    delete:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Housekeeping"
        '422':
          "$ref": "#/components/responses/UNPROCESSABLE_ENTITY"
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      summary: Delete all api specifications
      description: Delete all api specifications
      tags:
        - testing
  "/test/":
    get:
      responses:
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      tags:
        - testing
    post:
      responses:
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      tags:
        - testing
  "/test/time":
    get:
      responses:
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      tags:
        - testing
    post:
      responses:
        default:
          "$ref": "#/components/responses/DEFAULT_ERROR"
      tags:
        - testing
tags:
  - name: specs_api
    description: Collection and maintenance of specifications
  - name: proposals_api
    description: Collection and maintenance of spec proposals
  - name: comparison_api
    description: Comparing a api specification of a service to the latest spec and providing
      the changes.
  - name: merge_api
    description: Providing a proposed merge of two provided API specification in given
      context.
  - name: testing
    description: Endpoints for easier testing
openapi: 3.0.2
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        status:
          type: string
          description: Error name
        errors:
          type: object
          description: Errors
        code:
          type: integer
          description: Error code
    PaginationMetadata:
      type: object
      properties:
        total:
          type: integer
        total_pages:
          type: integer
        first_page:
          type: integer
        last_page:
          type: integer
        page:
          type: integer
        previous_page:
          type: integer
        next_page:
          type: integer
    ApiClaritySpecs:
      type: object
      properties:
        reconstructed_services:
          type: array
          items:
            type: string
    Services:
      type: object
      properties:
        services:
          type: array
          items:
            type: string
    Versions:
      type: object
      properties:
        versions:
          type: array
          items:
            type: string
    ApiSpecEntry:
      type: object
      properties:
        version:
          type: string
        created_at_date:
          type: string
        api_spec:
          type: object
        name:
          type: string
      required:
        - name
    ApiSpecs:
      type: object
      properties:
        api_specs:
          type: array
          items:
            "$ref": "#/components/schemas/ApiSpecEntry"
    Upload:
      type: object
      properties:
        file: {}
      required:
        - file
    UploadResponse:
      type: object
      properties:
        created_version:
          type: string
    Proposal:
      type: object
      properties:
        proposal:
          type: object
    Housekeeping:
      type: object
      properties:
        number_of_deleted:
          type: string
    NewEndpoint:
      type: object
      properties:
        method:
          type: string
          nullable: true
        path_is_new:
          type: boolean
        path_url:
          type: string
          nullable: true
        summary:
          type: string
          default:
          nullable: true
    MissingEndpoint:
      type: object
      properties:
        method:
          type: string
          nullable: true
        path_is_still_present:
          type: boolean
        path_url:
          type: string
          nullable: true
        summary:
          type: string
          default:
          nullable: true
    ChangedOperation:
      type: object
      properties:
        method:
          type: string
          nullable: true
        changed_fields:
          type: array
          nullable: true
          items:
            type: string
            nullable: true
        path_url:
          type: string
          nullable: true
    ApiDiffsResponse:
      type: object
      properties:
        new_endpoints:
          type: array
          nullable: true
          items:
            "$ref": "#/components/schemas/NewEndpoint"
        general_difference_given:
          type: boolean
          nullable: true
        missing_endpoints:
          type: array
          nullable: true
          items:
            "$ref": "#/components/schemas/MissingEndpoint"
        changed_operations:
          type: array
          nullable: true
          items:
            "$ref": "#/components/schemas/ChangedOperation"
        potentially_privacy_related_differences_given:
          type: boolean
          nullable: true
    SchemaTiraAnnotation:
      type: object
      properties:
        schema_tira_annotation:
          type: object
          nullable: true
        schema_name:
          type: string
          nullable: true
    ChangedSchemaTiraAnnotation:
      type: object
      properties:
        old_schema_tira_annotation:
          type: object
          nullable: true
        new_schema_tira_annotation:
          type: object
          nullable: true
        schema_name:
          type: string
          nullable: true
    ChangedGlobalTiraAnnotation:
      type: object
      properties:
        new_global_tira_annotation:
          type: object
          nullable: true
        old_global_tira_annotation:
          type: object
          nullable: true
        key:
          type: string
          nullable: true
    ApiDiffTira:
      type: object
      properties:
        missing_global_tira_annotation:
          type: array
          nullable: true
          items:
            type: object
        new_schema_tira_annotations:
          type: array
          nullable: true
          items:
            "$ref": "#/components/schemas/SchemaTiraAnnotation"
        changed_schema_tira_annotations:
          type: array
          nullable: true
          items:
            "$ref": "#/components/schemas/ChangedSchemaTiraAnnotation"
        missing_schema_tira_annotations:
          type: array
          nullable: true
          items:
            "$ref": "#/components/schemas/SchemaTiraAnnotation"
        new_global_tira_annotation:
          type: array
          nullable: true
          items:
            type: object
        changed_global_tira_annotation:
          type: array
          nullable: true
          items:
            nullable: true
            allOf:
              - "$ref": "#/components/schemas/ChangedGlobalTiraAnnotation"
    AllChangesComparison:
      type: object
      properties:
        api_diffs:
          nullable: true
          allOf:
            - "$ref": "#/components/schemas/ApiDiffsResponse"
        tira_diffs:
          nullable: true
          allOf:
            - "$ref": "#/components/schemas/ApiDiffTira"
        service:
          type: string
      required:
        - service
    ProposedMergeRequestBody:
      type: object
      properties:
        new_api:
          type: object
        old_api:
          type: object
  responses:
    DEFAULT_ERROR:
      description: Default error response
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
    UNPROCESSABLE_ENTITY:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
