apiVersion: v1
kind: Pod
metadata:
  name: postgrest
  labels:
    name: postgrest
spec:
  containers:
  - name: postgrest
    image: postgrest/postgrest
    ports:
      - name: http
        protocol: TCP
        containerPort: 3000
    env:
      - name: PGRST_DB_URI
        value: "postgres://postgres:apiclarity@apiclarity-apiclarity-postgresql.apiclarity.svc.cluster.local.:5432/apiclarity"
      - name: PGRST_DB_SCHEMA
        value: "public"
      - name: PGRST_DB_ANON_ROLE
        value: "postgres"