apiVersion: v1
kind: Service
metadata:
  name: apidiff-nodeport
  namespace: tapira
  labels:
    app: apidiff-nodeport
spec:
  type: NodePort
  selector:
    app: apidiff
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32230