---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidiff
  namespace: tapira
  labels:
    app: apidiff
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apidiff
      app: apidiff
  template:
    metadata:
      name: apidiff-pods
      namespace: tapira
      labels:
        name: apidiff
        app: apidiff
    spec:
      containers:
        - name: apidiff-containers
          image: milamber97/apidiff:latest
          ports:
            - containerPort: 8080