apiVersion: v1
kind: Service
metadata:
  name: apiclarity-nodeport
  namespace: apiclarity
  labels:
    app: apiclarity-nodeport
spec:
  type: NodePort
  selector:
    app: apiclarity-apiclarity
  ports:
    - port: 8080
      targetPort: 8080